import os
from dotenv import load_dotenv

load_dotenv()

SQLALCHEMY_DATABASE_URI = os.environ.get("SQLALCHEMY_DATABASE_URI")
SECRET_KEY = os.environ.get("SECRET_KEY")
ALGORITHM = os.environ.get("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.environ.get("ACCESS_TOKEN_EXPIRE_MINUTES", 1))
DEFAULT_USER_BALANCE = float(os.environ.get("DEFAULT_USER_BALANCE", 1))
SESSION_EXPIRES = int(os.environ.get("SESSION_EXPIRES", 1))
OTP_EXPIRES = int(os.environ.get("OTP_EXPIRES", 1))
EXCEPTION_MESSAGE = os.environ.get("EXCEPTION_MESSAGE", "Network Error")
REDIS_URL = os.environ.get("REDIS_URL")
EMAIL_USER = os.environ.get("EMAIL_USER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
SMTP_HOST = os.environ.get("SMTP_HOST")
SMTP_PORT = os.environ.get("SMTP_PORT")
FROM_EMAIL = os.environ.get("FROM_EMAIL")
ALLOWED_ORIGINS = os.environ.get("ALLOWED_ORIGINS")
ALLOWED_METHODS = os.environ.get("ALLOWED_METHODS")
ALLOWED_HEADERS = os.environ.get("ALLOWED_HEADERS")
REDIS_HOST = os.environ.get("REDIS_HOST")
REDIS_PORT = os.environ.get("REDIS_PORT")
RATE_LIMIT = int(os.environ.get("RATE_LIMIT"))
WINDOW_SECONDS = int(os.environ.get("WINDOW_SECONDS"))
MAINTENANCE_MODE = bool(int(os.environ.get("MAINTENANCE_MODE")))
FILE_NAME = os.environ.get("FILE_NAME")
API_VERSION = os.environ.get("API_VERSION")
