services:
  api:
    image: hr_mgt
    container_name: hr_mgt
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "0.0.0.0:7011:7011"
    volumes:
      - .:/app
    networks:
      - HrNetwork
    env_file:
      - .env
#    depends_on:
#      - redis

#  redis:
#    image: redis
#    container_name: hr-redis
#    networks:
#      - HrNetwork
#    volumes:
#      - redis_data:/data
#    ports:
#      - "127.0.0.1:6380:6379"
#    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
#    env_file:
#      - .env
#
#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile.celery
#    restart: always
#    container_name: hr-celery
#    networks:
#      - HrNetwork
#    env_file:
#      - .env
#    depends_on:
#      - redis


networks:
  HrNetwork:
    driver: bridge

#volumes:
#  redis_data:
