"""overv

Revision ID: 12cf0b11bad8
Revises: da986af8b2e7
Create Date: 2026-06-01 15:29:56.242357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cf0b11bad8'
down_revision: Union[str, None] = 'da986af8b2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('overview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'overview')
    # ### end Alembic commands ###
