"""dept

Revision ID: 229ac6b50e6b
Revises: 898c92683dc3
Create Date: 2025-12-16 12:43:49.467332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229ac6b50e6b'
down_revision: Union[str, None] = '898c92683dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('organization_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'departments', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'organization_id')
    # ### end Alembic commands ###
