"""New Column 2

Revision ID: 367556e0a6e2
Revises: adfbe591ce2c
Create Date: 2025-05-23 12:08:13.676607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "367556e0a6e2"
down_revision: Union[str, None] = "adfbe591ce2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    sa.Enum("PAYSLIP", "PERSONAL", name="filetype").create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploaded_files",
        sa.Column(
            "file_type", sa.Enum("PAYSLIP", "PERSONAL", name="filetype"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploaded_files", "file_type")
    # ### end Alembic commands ###
