"""Added Join Date to Users Table

Revision ID: 3858fe15f68b
Revises: f6f0f61fe263
Create Date: 2025-05-19 15:03:18.595839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3858fe15f68b'
down_revision: Union[str, None] = 'f6f0f61fe263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_date')
    # ### end Alembic commands ###
