"""position_parent

Revision ID: 44ea8d20b749
Revises: 12cf0b11bad8
Create Date: 2026-06-04 13:05:13.620773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ea8d20b749'
down_revision: Union[str, None] = '12cf0b11bad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('parent_id', sa.String(length=50), nullable=True))
    op.add_column('departments', sa.Column('position', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'position')
    op.drop_column('departments', 'parent_id')
    # ### end Alembic commands ###
