"""Create new column

Revision ID: 471ed2b160a6
Revises: edf9544ba088
Create Date: 2025-05-14 16:24:29.619358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "471ed2b160a6"
down_revision: Union[str, None] = "edf9544ba088"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions", sa.Column("salt", sa.String(length=70), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sessions", "salt")
    # ### end Alembic commands ###
