"""False_True

Revision ID: 59a74ddd85d1
Revises: 229ac6b50e6b
Create Date: 2025-12-17 15:39:09.670430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a74ddd85d1'
down_revision: Union[str, None] = '229ac6b50e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applied_candidates', 'cover_letter',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applied_candidates', 'cover_letter',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
