"""job_postings

Revision ID: 898c92683dc3
Revises: 90b0096d7da1
Create Date: 2025-12-16 12:17:24.849115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898c92683dc3'
down_revision: Union[str, None] = '90b0096d7da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_stages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_posting',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posting_department_id'), 'job_posting', ['department_id'], unique=False)
    op.create_index(op.f('ix_job_posting_job_type'), 'job_posting', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_posting_organization_id'), 'job_posting', ['organization_id'], unique=False)
    op.create_index(op.f('ix_job_posting_status'), 'job_posting', ['status'], unique=False)
    op.create_table('applied_candidates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('job_posting_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=150), nullable=False),
    sa.Column('resume', sa.String(length=200), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('job_stage_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_posting.id'], ),
    sa.ForeignKeyConstraint(['job_stage_id'], ['job_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applied_candidates_job_posting_id'), 'applied_candidates', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_applied_candidates_job_stage_id'), 'applied_candidates', ['job_stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applied_candidates_job_stage_id'), table_name='applied_candidates')
    op.drop_index(op.f('ix_applied_candidates_job_posting_id'), table_name='applied_candidates')
    op.drop_table('applied_candidates')
    op.drop_index(op.f('ix_job_posting_status'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_organization_id'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_job_type'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_department_id'), table_name='job_posting')
    op.drop_table('job_posting')
    op.drop_table('job_stages')
    # ### end Alembic commands ###
