"""Add to bank details

Revision ID: 90b0096d7da1
Revises: d1753a9f2c87
Create Date: 2025-12-15 11:45:26.417875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b0096d7da1'
down_revision: Union[str, None] = 'd1753a9f2c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_details', sa.Column('account_name', sa.String(length=100), nullable=True))
    op.alter_column('bank_details', 'bank_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_details', 'bank_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('bank_details', 'account_name')
    # ### end Alembic commands ###
