"""postal code col

Revision ID: a9ec9ce48ee1
Revises: 367556e0a6e2
Create Date: 2025-10-02 16:45:03.155123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9ec9ce48ee1'
down_revision: Union[str, None] = '367556e0a6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_employment')
    op.add_column('user_profile', sa.Column('postal_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'postal_code')
    op.create_table('user_employment',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('employment_status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'ON_BOARDING', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED', 'PROBATION', 'RESIGNED', name='employmentstatus'), autoincrement=False, nullable=False),
    sa.Column('employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'FREELANCE', 'VOLUNTEER', name='employmenttype'), autoincrement=False, nullable=False),
    sa.Column('work_mode', postgresql.ENUM('ONSITE', 'REMOTE', 'HYBRID', name='workmode'), autoincrement=False, nullable=False),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_employment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_employment_pkey'),
    sa.UniqueConstraint('user_id', name='user_employment_user_id_key')
    )
    # ### end Alembic commands ###
