"""New Column

Revision ID: adfbe591ce2c
Revises: 5ef64e2afe1e
Create Date: 2025-05-23 12:05:31.457220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adfbe591ce2c'
down_revision: Union[str, None] = '5ef64e2afe1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compensation',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('compensation_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('user_employment')
    op.add_column('employment_details', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.drop_column('employment_details', 'salary')
    op.add_column('user_profile', sa.Column('tax_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'tax_id')
    op.add_column('employment_details', sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('employment_details', 'join_date')
    op.create_table('user_employment',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('employment_status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'ON_BOARDING', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED', 'PROBATION', 'RESIGNED', name='employmentstatus'), autoincrement=False, nullable=False),
    sa.Column('employment_type', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'FREELANCE', 'VOLUNTEER', name='employmenttype'), autoincrement=False, nullable=False),
    sa.Column('work_mode', postgresql.ENUM('ONSITE', 'REMOTE', 'HYBRID', name='workmode'), autoincrement=False, nullable=False),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_employment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_employment_pkey'),
    sa.UniqueConstraint('user_id', name='user_employment_user_id_key')
    )
    op.drop_table('compensation')
    # ### end Alembic commands ###
