"""org_id

Revision ID: bcbdd2282997
Revises: 59a74ddd85d1
Create Date: 2025-12-18 10:53:27.867339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbdd2282997'
down_revision: Union[str, None] = '59a74ddd85d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_stages', sa.Column('organization_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'job_stages', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_stages', type_='foreignkey')
    op.drop_column('job_stages', 'organization_id')
    # ### end Alembic commands ###
