"""browser_id

Revision ID: cfa888265223
Revises: bcbdd2282997
Create Date: 2025-12-18 11:37:57.163317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa888265223'
down_revision: Union[str, None] = 'bcbdd2282997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applied_candidates', sa.Column('browser_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applied_candidates', 'browser_id')
    # ### end Alembic commands ###
