"""priority

Revision ID: da986af8b2e7
Revises: cfa888265223
Create Date: 2026-01-08 11:41:18.835994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da986af8b2e7'
down_revision: Union[str, None] = 'cfa888265223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_stages', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_stages', 'priority')
    # ### end Alembic commands ###
