"""Create new column

Revision ID: edf9544ba088
Revises: 1c31bd38039e
Create Date: 2025-05-14 14:43:48.575846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edf9544ba088"
down_revision: Union[str, None] = "1c31bd38039e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reasons", sa.Column("description", sa.String(length=200), nullable=True)
    )
    op.drop_column("reasons", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reasons",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("reasons", "description")
    # ### end Alembic commands ###
