"""Modified and Removed Tables side menu

Revision ID: f6f0f61fe263
Revises: f7779016362e
Create Date: 2025-05-19 13:57:06.391666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6f0f61fe263"
down_revision: Union[str, None] = "f7779016362e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("side_menu")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "side_menu",
        sa.Column("id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=70), autoincrement=False, nullable=False),
        sa.Column("icon", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column("tag", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="side_menu_pkey"),
        sa.UniqueConstraint("tag", name="side_menu_tag_key"),
    )
    # ### end Alembic commands ###
