"""Modified and Removed Tables SUbside menu

Revision ID: f7779016362e
Revises: ea239a132dd0
Create Date: 2025-05-19 13:55:54.681503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7779016362e"
down_revision: Union[str, None] = "ea239a132dd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sub_side_menu")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_side_menu",
        sa.Column("id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=70), autoincrement=False, nullable=False),
        sa.Column(
            "side_menu_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["side_menu_id"], ["side_menu.id"], name="sub_side_menu_side_menu_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="sub_side_menu_pkey"),
    )
    # ### end Alembic commands ###
